spring.application.name=api-gateway
server.port=8080

# =========================
# Eureka
# =========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=8080
eureka.instance.instance-id=api-gateway:8080

# =========================
# Gateway Routes
# =========================

# Product Service
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/**

# Order Service
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**

# Payment Service
spring.cloud.gateway.server.webflux.routes[2].id=payment-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/payments/**

# Notification Service
spring.cloud.gateway.server.webflux.routes[3].id=notification-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/notifications/**

# Inventory Service
spring.cloud.gateway.server.webflux.routes[4].id=inventory-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/inventory/**

# Auth Service
spring.cloud.gateway.server.webflux.routes[5].id=auth-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/auth/**
