spring.application.name=order-service
server.port=8083

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Eureka Instance
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=8083
eureka.instance.instance-id=order-service:8083

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all

# Kafka Producer Retry
spring.kafka.producer.retries=3
spring.kafka.producer.properties.retry.backoff.ms=1000

# Consumer
spring.kafka.consumer.group-id=order-payment-group
spring.kafka.consumer.auto-offset-reset=latest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.smartshopping.*
spring.kafka.consumer.properties.spring.json.value.default.type=com.smartshopping.orderservice.event.PaymentProcessedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false
